export enum CategoryEnum {
  ALL = 'All',
  ACTION = 'Action',
  ADVENTURE = 'Adventure',
  ALTERNATE_HISTORY = 'Alternate_history',
  ANTHOLOGY = 'Anthology',
  CHILDERN = 'Children',
  CLASSIC = 'Classic',
  COMIC_BOOK = 'Comic book',
  CRIME = 'Crime',
  DRAMA = 'Drama',
  FAIRYTALE = 'Fairytale',
  FANTASY = 'Fantasy',
  HORROR = 'Horror',
  MYSTERY = 'Mystery',
  PICTURE_BOOK = 'Picture book',
  ROMANCE = 'Romance',
  BIOGRAPHY = 'Biography',
  HEALTH = 'Health',
}
